version: "3.9"

services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.12
    container_name: twilio-admin-api
    restart: always
    environment:
      MODULE_NAME: app.main
      VARIABLE_NAME: app
      JWT_SECRET: "change-me"
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
      VERIFY_SERVICE_SID: "${VERIFY_SERVICE_SID}"
      SYNC_SERVICE_SID: "${SYNC_SERVICE_SID}"
    volumes:
      - ./api/app:/app
      - ./api/requirements.txt:/tmp/requirements.txt:ro
    command: /bin/sh -lc "pip install --no-cache-dir -r /tmp/requirements.txt && /start.sh"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [dokploy-network]

  # One-off build job that writes the compiled site into a named volume
  web-build:
    image: node:20-alpine
    container_name: twilio-admin-web-build
    working_dir: /src
    volumes:
      - ./web:/src
      - web_dist:/out
    command: >
      sh -lc "npm ci && npm run build && rm -rf /out/* && cp -r dist/* /out/"
    networks: [dokploy-network]
    # You can disable this service after the first deploy if you won't rebuild often.

  web:
    image: nginx:alpine
    container_name: twilio-admin-web
    restart: always
    depends_on:
      web-build:
        condition: service_completed_successfully
    volumes:
      - web_dist:/usr/share/nginx/html:ro
    ports:
      - ":80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 15s
      timeout: 3s
      retries: 5
    networks: [dokploy-network]

networks:
  dokploy-network:
    external: true

volumes:
  web_dist:
